[package]
name = "tarantula"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.48", features = ["derive"]}
dirs = "6.0.0"
exec = "0.3.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.23.0"
uuid = "1.18.1"
